structure(list(url = "https://api.sleeper.app/v1/user/solarpool", 
    status_code = 200L, headers = structure(list(date = "Tue, 11 Aug 2020 12:29:50 GMT", 
        `content-type` = "application/json; charset=utf-8", `transfer-encoding` = "chunked", 
        connection = "keep-alive", vary = "Accept-Encoding", 
        `cache-control` = "max-age=0, private, must-revalidate", 
        `x-request-id` = "0b1ad48c1ef2142a2a990f5609c52ffd", 
        `access-control-allow-origin` = "*", `access-control-expose-headers` = "etag", 
        `access-control-allow-credentials` = "true", `strict-transport-security` = "max-age=15724800; includeSubDomains", 
        `content-encoding` = "gzip", `cf-cache-status` = "BYPASS", 
        `cf-request-id` = "047f18a26d000074cb2c2ba200000001", 
        `expect-ct` = "max-age=604800, report-uri=\"https://report-uri.cloudflare.com/cdn-cgi/beacon/expect-ct\"", 
        server = "cloudflare", `cf-ray` = "5c11f6e3ef9374cb-IAD"), class = c("insensitive", 
    "list")), all_headers = list(list(status = 200L, version = "HTTP/1.1", 
        headers = structure(list(date = "Tue, 11 Aug 2020 12:29:50 GMT", 
            `content-type` = "application/json; charset=utf-8", 
            `transfer-encoding` = "chunked", connection = "keep-alive", 
            vary = "Accept-Encoding", `cache-control` = "max-age=0, private, must-revalidate", 
            `x-request-id` = "0b1ad48c1ef2142a2a990f5609c52ffd", 
            `access-control-allow-origin` = "*", `access-control-expose-headers` = "etag", 
            `access-control-allow-credentials` = "true", `strict-transport-security` = "max-age=15724800; includeSubDomains", 
            `content-encoding` = "gzip", `cf-cache-status` = "BYPASS", 
            `cf-request-id` = "047f18a26d000074cb2c2ba200000001", 
            `expect-ct` = "max-age=604800, report-uri=\"https://report-uri.cloudflare.com/cdn-cgi/beacon/expect-ct\"", 
            server = "cloudflare", `cf-ray` = "5c11f6e3ef9374cb-IAD"), class = c("insensitive", 
        "list")))), cookies = structure(list(domain = "#HttpOnly_.sleeper.app", 
        flag = TRUE, path = "/", secure = TRUE, expiration = structure(1599740860, class = c("POSIXct", 
        "POSIXt")), name = "__cfduid", value = "REDACTED"), row.names = c(NA, 
    -1L), class = "data.frame"), content = charToRaw("{\"verification\":null,\"username\":\"solarpool\",\"user_id\":\"202892038360801280\",\"token\":null,\"solicitable\":null,\"real_name\":null,\"phone\":null,\"pending\":null,\"notifications\":null,\"is_bot\":false,\"email\":null,\"display_name\":\"solarpool\",\"deleted\":null,\"data_updated\":null,\"currencies\":null,\"created\":null,\"cookies\":null,\"avatar\":\"a71f864896ba28cbfaa4dc5df5b564e0\"}"), 
    date = structure(1597148990, class = c("POSIXct", "POSIXt"
    ), tzone = "GMT"), times = c(redirect = 0, namelookup = 7.1e-05, 
    connect = 7.4e-05, pretransfer = 0.000201, starttransfer = 0.147603, 
    total = 0.148319)), class = "response")
