structure(list(url = "https://api.sleeper.app/v1/user/solarpool", 
    status_code = 200L, headers = structure(list(date = "Wed, 12 Aug 2020 11:52:27 GMT", 
        `content-type` = "application/json; charset=utf-8", `transfer-encoding` = "chunked", 
        connection = "keep-alive", `set-cookie` = "REDACTED", 
        vary = "Accept-Encoding", `cache-control` = "max-age=0, private, must-revalidate", 
        `x-request-id` = "ff9a5b831e4c50199adf9176ac6d2706", 
        `access-control-allow-origin` = "*", `access-control-expose-headers` = "etag", 
        `access-control-allow-credentials` = "true", `strict-transport-security` = "max-age=15724800; includeSubDomains", 
        `content-encoding` = "gzip", `cf-cache-status` = "BYPASS", 
        `cf-request-id` = "04841cc3080000ea386334c200000001", 
        `expect-ct` = "max-age=604800, report-uri=\"https://report-uri.cloudflare.com/cdn-cgi/beacon/expect-ct\"", 
        server = "cloudflare", `cf-ray` = "5c19fd7e7bf2ea38-IAD"), class = c("insensitive", 
    "list")), all_headers = list(list(status = 200L, version = "HTTP/1.1", 
        headers = structure(list(date = "Wed, 12 Aug 2020 11:52:27 GMT", 
            `content-type` = "application/json; charset=utf-8", 
            `transfer-encoding` = "chunked", connection = "keep-alive", 
            `set-cookie` = "REDACTED", vary = "Accept-Encoding", 
            `cache-control` = "max-age=0, private, must-revalidate", 
            `x-request-id` = "ff9a5b831e4c50199adf9176ac6d2706", 
            `access-control-allow-origin` = "*", `access-control-expose-headers` = "etag", 
            `access-control-allow-credentials` = "true", `strict-transport-security` = "max-age=15724800; includeSubDomains", 
            `content-encoding` = "gzip", `cf-cache-status` = "BYPASS", 
            `cf-request-id` = "04841cc3080000ea386334c200000001", 
            `expect-ct` = "max-age=604800, report-uri=\"https://report-uri.cloudflare.com/cdn-cgi/beacon/expect-ct\"", 
            server = "cloudflare", `cf-ray` = "5c19fd7e7bf2ea38-IAD"), class = c("insensitive", 
        "list")))), cookies = structure(list(domain = "#HttpOnly_.sleeper.app", 
        flag = TRUE, path = "/", secure = TRUE, expiration = structure(1599825146, class = c("POSIXct", 
        "POSIXt")), name = "__cfduid", value = "REDACTED"), row.names = c(NA, 
    -1L), class = "data.frame"), content = charToRaw("{\"verification\":null,\"username\":\"solarpool\",\"user_id\":\"202892038360801280\",\"token\":null,\"solicitable\":null,\"real_name\":null,\"phone\":null,\"pending\":null,\"notifications\":null,\"is_bot\":false,\"email\":null,\"display_name\":\"solarpool\",\"deleted\":null,\"data_updated\":null,\"currencies\":null,\"created\":null,\"cookies\":null,\"avatar\":\"a71f864896ba28cbfaa4dc5df5b564e0\"}"), 
    date = structure(1597233147, class = c("POSIXct", "POSIXt"
    ), tzone = "GMT"), times = c(redirect = 0, namelookup = 0.020192, 
    connect = 0.053472, pretransfer = 0.129792, starttransfer = 0.599056, 
    total = 0.60043)), class = "response")
