structure(list(url = "https://www.fleaflicker.com/api/FetchLeagueRosters?sport=NFL", 
    status_code = 404L, headers = structure(list(date = "Thu, 19 Nov 2020 17:22:32 GMT", 
        `content-type` = "application/json;charset=utf-8", `transfer-encoding` = "chunked", 
        connection = "keep-alive", vary = "accept-encoding", 
        `content-encoding` = "gzip"), class = c("insensitive", 
    "list")), all_headers = list(list(status = 404L, version = "HTTP/1.1", 
        headers = structure(list(date = "Thu, 19 Nov 2020 17:22:32 GMT", 
            `content-type` = "application/json;charset=utf-8", 
            `transfer-encoding` = "chunked", connection = "keep-alive", 
            vary = "accept-encoding", `content-encoding` = "gzip"), class = c("insensitive", 
        "list")))), cookies = structure(list(domain = logical(0), 
        flag = logical(0), path = logical(0), secure = logical(0), 
        expiration = structure(numeric(0), class = c("POSIXct", 
        "POSIXt")), name = logical(0), value = logical(0)), row.names = integer(0), class = "data.frame"), 
    content = charToRaw("{\"message\":\"Not found\"}"), date = structure(1605806552, class = c("POSIXct", 
    "POSIXt"), tzone = "GMT"), times = c(redirect = 0, namelookup = 0.0584, 
    connect = 0.085354, pretransfer = 0.145523, starttransfer = 0.174188, 
    total = 0.174226)), class = "response")
