structure(list(url = "https://www.fleaflicker.com/api/FetchUserLeagues?season=2020&sport=NFL", 
    status_code = 404L, headers = structure(list(date = "Thu, 19 Nov 2020 16:59:55 GMT", 
        `content-type` = "application/json;charset=utf-8", `transfer-encoding` = "chunked", 
        connection = "keep-alive", vary = "accept-encoding", 
        `content-encoding` = "gzip"), class = c("insensitive", 
    "list")), all_headers = list(list(status = 404L, version = "HTTP/1.1", 
        headers = structure(list(date = "Thu, 19 Nov 2020 16:59:55 GMT", 
            `content-type` = "application/json;charset=utf-8", 
            `transfer-encoding` = "chunked", connection = "keep-alive", 
            vary = "accept-encoding", `content-encoding` = "gzip"), class = c("insensitive", 
        "list")))), cookies = structure(list(domain = logical(0), 
        flag = logical(0), path = logical(0), secure = logical(0), 
        expiration = structure(numeric(0), class = c("POSIXct", 
        "POSIXt")), name = logical(0), value = logical(0)), row.names = integer(0), class = "data.frame"), 
    content = charToRaw("{\"message\":\"No email/userId specified and not signed in\"}"), 
    date = structure(1605805195, class = c("POSIXct", "POSIXt"
    ), tzone = "GMT"), times = c(redirect = 0, namelookup = 7.1e-05, 
    connect = 7.3e-05, pretransfer = 0.000249, starttransfer = 0.029206, 
    total = 0.029249)), class = "response")
